### ISSUE TITLE
Listener leak on MultiplexSocket during reconnect

### ISSUE THREAD

**Issue by jcheng5** [rstudio/shiny-server#195]
Reconnecting a bunch of times gives you this:

```
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at addListener (events.js:160:15)
    at new MultiplexSocket (/home/jcheng/development/shiny-server/lib/proxy/multiplex.js:47:8)
    at onMultiplexConnect (/home/jcheng/development/shiny-server/lib/proxy/sockjs.js:54:20)
    at Server.<anonymous> (/home/jcheng/development/shiny-server/lib/proxy/sockjs.js:43:7)
    at Server.emit (events.js:95:17)
    at App.emit (/home/jcheng/development/shiny-server/node_modules/sockjs/lib/sockjs.js:193:29)
    at /home/jcheng/development/shiny-server/node_modules/sockjs/lib/transport.js:111:25
    at process._tickCallback (node.js:448:13)
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at addListener (events.js:160:15)
    at new MultiplexSocket (/home/jcheng/development/shiny-server/lib/proxy/multiplex.js:55:8)
    at onMultiplexConnect (/home/jcheng/development/shiny-server/lib/proxy/sockjs.js:54:20)
    at Server.<anonymous> (/home/jcheng/development/shiny-server/lib/proxy/sockjs.js:43:7)
    at Server.emit (events.js:95:17)
    at App.emit (/home/jcheng/development/shiny-server/node_modules/sockjs/lib/sockjs.js:193:29)
    at /home/jcheng/development/shiny-server/node_modules/sockjs/lib/transport.js:111:25
    at process._tickCallback (node.js:448:13)
```

**Comment by detule** [comment]
Hi Joe

Did you ever figure this out?
Perhaps not relevant post-refactor, but couple of months ago I [pinged Jeff](https://github.com/rstudio/shiny-server/commit/50530e13436ce4c027dfd058a5b6c679cbb2ea8b#commitcomment-15619357) about something similar.

Cheers.
