### ISSUE TITLE
Crash of shiny-server within robust-sockjs because conn is null

### ISSUE THREAD

**Issue by Thoro** [rstudio/shiny-server#454]
Hi,

I just experienced a crash of shiny-server with the following stacktrace:

```
[2020-07-07T05:55:28.720] [INFO] shiny-server - Shutting down worker processes (with notification)
/opt/shiny-server/lib/main.js:387
  throw err;
  ^

TypeError: Cannot read property 'url' of null
    at getInfo (/opt/shiny-server/lib/proxy/robust-sockjs.js:29:46)
    at RobustSockJSRegistry.robustify (/opt/shiny-server/lib/proxy/robust-sockjs.js:59:16)
    at Server.<anonymous> (/opt/shiny-server/lib/proxy/sockjs.js:50:29)
    at Server.emit (events.js:223:5)
    at App.emit (/opt/shiny-server/node_modules/sockjs/lib/sockjs.js:196:29)
    at /opt/shiny-server/node_modules/sockjs/lib/transport.js:111:25
    at processTicksAndRejections (internal/process/task_queues.js:76:11)
```

I sadly do not know how to reproduce this.

**Comment by mfernandes61** [comment]
we have had this happen too - during a stats class. was working fine when just me testing but then under load...

**Comment by jcheng5** [comment]
I’m so sorry to hear that. I’ve been trying to reproduce this myself, with little success.

**Comment by neslonik** [comment]
Hi @jcheng5 We started experiencing the same problem:

[2021-07-13T12:02:38.088] [ERROR] shiny-server - Uncaught exception: TypeError: Cannot read property 'url' of null
[2021-07-13T12:02:38.094] [ERROR] shiny-server - TypeError: Cannot read property 'url' of null
at getInfo (/data/shiny-server-1.5.16-build/shiny-server/lib/proxy/robust-sockjs.js:29:46)
at RobustSockJSRegistry.robustify (/data/shiny-server-1.5.16-build/shiny-server/lib/proxy/robust-sockjs.js:59:16)
at Server.<anonymous> (/data/shiny-server-1.5.16-build/shiny-server/lib/proxy/sockjs.js:50:29)
at Server.emit (events.js:314:20)
at App.emit (/data/shiny-server-1.5.16-build/shiny-server/node_modules/sockjs/lib/sockjs.js:196:29)
at /data/shiny-server-1.5.16-build/shiny-server/node_modules/sockjs/lib/transport.js:111:25
at processTicksAndRejections (internal/process/task_queues.js:79:11)
[2021-07-13T12:02:38.095] [INFO] shiny-server - Stopping listener on http://[::]:3838
[2021-07-13T12:02:38.096] [INFO] shiny-server - Shutting down worker processes (with notification)
/data/shiny-server-1.5.16-build/shiny-server/lib/main.js:387
throw err;
^

TypeError: Cannot read property 'url' of null
at getInfo (/data/shiny-server-1.5.16-build/shiny-server/lib/proxy/robust-sockjs.js:29:46)
at RobustSockJSRegistry.robustify (/data/shiny-server-1.5.16-build/shiny-server/lib/proxy/robust-sockjs.js:59:16)
at Server.<anonymous> (/data/shiny-server-1.5.16-build/shiny-server/lib/proxy/sockjs.js:50:29)
at Server.emit (events.js:314:20)
at App.emit (/data/shiny-server-1.5.16-build/shiny-server/node_modules/sockjs/lib/sockjs.js:196:29)
at /data/shiny-server-1.5.16-build/shiny-server/node_modules/sockjs/lib/transport.js:111:25
at processTicksAndRejections (internal/process/task_queues.js:79:11)
[2021-07-13T12:06:52.562] [INFO] shiny-server - Shiny Server v1.5.16.0 (Node.js v12.20.0)

Is there anything we can do to have additional log/tracing? 

This happens with only one rather highly used app.


Thank you.
Alla
